#%RAML 1.0
title: Citadel REST API
version: v1
schemas:
  - Metadata: |
     { 
       "$schema": "http://json-schema.org/draft-03/schema",
       "type": "object",
       "properties": {
         "srcid": { "type": "string"},
         "unit": { "type": "string"},
         "pointType": { "type": "string"}
       }
     }
  - Datum: |
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "properties": {
          "srcid": { "type": "string"},
          "value": { "type": "double"},
          "geometryType": { "type": "string"},
          "coordinates": [[{"type": "double"}]]
        }
      }
  - Data: |
      [
        schema: Datum
      ]

/api:
  get:
    responses:
      200:
        body:
          {API Documentation}
  /point:
    post:
      responses:
        201:
          body:
            application/json:
              example: 
    /{srcid}
      get:
        responses:
          200:
            body:
              application/json:
                schema: Metadata
  /data:
    get:
      responses:
        200:
    post:
      bpdy:
        application/json:
          schema: Data
      responses:
        201:
          body:
            {}
  /query:
    post:
      body:
        application/json:
          {}
      responses:
        200:
          body:
            application/json:
              schema: |
                {}
  /querydata:
    post:
      body:
        application/json:
          {}
      responses: 
        200:
          body:
            application/json:
              schema: |
                {}
