#!/bin/python

sudo docker run --rm --name citadel-mongodb -itd mongo
sudo docker run --rm --name citadel-influxdb -itd influxdb
sudo docker run --rm -p 80:80 --name citadel-instance -itd jbkoh/citadel



